/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTopologyBindingLister helps list ClusterTopologyBindings.
// All objects returned here must be treated as read-only.
type ClusterTopologyBindingLister interface {
	// List lists all ClusterTopologyBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.ClusterTopologyBinding, err error)
	// Get retrieves the ClusterTopologyBinding from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.ClusterTopologyBinding, error)
	ClusterTopologyBindingListerExpansion
}

// clusterTopologyBindingLister implements the ClusterTopologyBindingLister interface.
type clusterTopologyBindingLister struct {
	listers.ResourceIndexer[*corev1alpha1.ClusterTopologyBinding]
}

// NewClusterTopologyBindingLister returns a new ClusterTopologyBindingLister.
func NewClusterTopologyBindingLister(indexer cache.Indexer) ClusterTopologyBindingLister {
	return &clusterTopologyBindingLister{listers.New[*corev1alpha1.ClusterTopologyBinding](indexer, corev1alpha1.Resource("clustertopologybinding"))}
}
