/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodGangMapLister helps list PodGangMaps.
// All objects returned here must be treated as read-only.
type PodGangMapLister interface {
	// List lists all PodGangMaps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodGangMap, err error)
	// PodGangMaps returns an object that can list and get PodGangMaps.
	PodGangMaps(namespace string) PodGangMapNamespaceLister
	PodGangMapListerExpansion
}

// podGangMapLister implements the PodGangMapLister interface.
type podGangMapLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodGangMap]
}

// NewPodGangMapLister returns a new PodGangMapLister.
func NewPodGangMapLister(indexer cache.Indexer) PodGangMapLister {
	return &podGangMapLister{listers.New[*corev1alpha1.PodGangMap](indexer, corev1alpha1.Resource("podgangmap"))}
}

// PodGangMaps returns an object that can list and get PodGangMaps.
func (s *podGangMapLister) PodGangMaps(namespace string) PodGangMapNamespaceLister {
	return podGangMapNamespaceLister{listers.NewNamespaced[*corev1alpha1.PodGangMap](s.ResourceIndexer, namespace)}
}

// PodGangMapNamespaceLister helps list and get PodGangMaps.
// All objects returned here must be treated as read-only.
type PodGangMapNamespaceLister interface {
	// List lists all PodGangMaps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodGangMap, err error)
	// Get retrieves the PodGangMap from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.PodGangMap, error)
	PodGangMapNamespaceListerExpansion
}

// podGangMapNamespaceLister implements the PodGangMapNamespaceLister
// interface.
type podGangMapNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodGangMap]
}
