apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: volcano-gang-qa-queue
  annotations:
    scheduling.grove.io/volcano-queue: qa-volcano-e2e
spec:
  replicas: 1
  template:
    cliques:
      - name: frontend
        spec:
          roleName: frontend
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: volcano
            terminationGracePeriodSeconds: 1
            containers:
              - name: frontend
                image: alpine
                imagePullPolicy: IfNotPresent
                command: ["sh", "-c", "sleep 3600"]
                resources:
                  requests:
                    cpu: 5m
                    memory: 16Mi
      - name: backend
        spec:
          roleName: backend
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: volcano
            terminationGracePeriodSeconds: 1
            containers:
              - name: backend
                image: alpine
                imagePullPolicy: IfNotPresent
                command: ["sh", "-c", "sleep 3600"]
                resources:
                  requests:
                    cpu: 5m
                    memory: 16Mi
