/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	versioned "github.com/ai-dynamo/grove/operator/client/clientset/versioned"
	internalinterfaces "github.com/ai-dynamo/grove/operator/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/ai-dynamo/grove/operator/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTopologyBindingInformer provides access to a shared informer and lister for
// ClusterTopologyBindings.
type ClusterTopologyBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.ClusterTopologyBindingLister
}

type clusterTopologyBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterTopologyBindingInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().Watch(ctx, options)
			},
		},
		&apicorev1alpha1.ClusterTopologyBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterTopologyBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterTopologyBindingInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterTopologyBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha1.ClusterTopologyBinding{}, f.defaultInformer)
}

func (f *clusterTopologyBindingInformer) Lister() corev1alpha1.ClusterTopologyBindingLister {
	return corev1alpha1.NewClusterTopologyBindingLister(f.Informer().GetIndexer())
}
