apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: grove-operator
build:
  local: # see https://skaffold.dev/docs/builders/build-environments/local/
    push: true
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: grove-operator
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - cmd
            - initc
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
    - image: grove-initc
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - initc
            - internal
            - VERSION
        flags:
          - -v
        main: ./initc/cmd
    - image: grove-install-crds
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - cmd/install-crds
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/install-crds
deploy:
  helm: # see https://skaffold.dev/docs/deployers/helm/
    releases:
      - name: grove-operator
        chartPath: charts
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: "{{.VERSION}}@{{.IMAGE_DIGEST}}"
          crdInstaller.image.repository: '{{.IMAGE_REPO_grove_install_crds}}'
          crdInstaller.image.tag: "{{.VERSION}}@{{.IMAGE_DIGEST_grove_install_crds}}"
          deployment.env:
            - name: GROVE_INIT_CONTAINER_IMAGE
              value: "{{.CONTAINER_REGISTRY}}/grove-initc"
        skipBuildDependencies: true
        createNamespace: true
        wait: true
profiles:
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config:
            leaderElection:
              enabled: false
  - name: topology-test
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config:
            scheduler:
              defaultProfileName: kai-scheduler
              profiles:
                - name: kai-scheduler
            leaderElection:
              enabled: false
            topologyAwareScheduling:
              enabled: true
  - name: mnnvl-test
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config:
            leaderElection:
              enabled: false
            network:
              autoMNNVLEnabled: true
